import type { ComplianceReport, FontReadabilityAudit, RuleEvaluationDetail, ViolationDetail } from '../types';

// ── Font & Readability Audit per Rule 9 Table I of LMPC Rules, 2011 ──────────
export const DEMO_FONT_AUDITS: FontReadabilityAudit[] = [
  {
    field: 'mrp',
    label: 'MRP Numeral Height',
    detected_height_mm: 3.2,
    required_height_mm: 2.0, // For net weight 100g-500g
    status: 'PASS',
    standard_rule: 'Rule 9, Table I (Net qty 100g-500g req min 2.0mm)',
  },
  {
    field: 'net_quantity',
    label: 'Net Quantity Numeral Height',
    detected_height_mm: 2.8,
    required_height_mm: 2.0,
    status: 'PASS',
    standard_rule: 'Rule 9, Table I (Net qty 100g-500g req min 2.0mm)',
  },
  {
    field: 'manufacturer_name',
    label: 'Packer Address Font Height',
    detected_height_mm: 1.4,
    required_height_mm: 1.5,
    status: 'FAIL',
    standard_rule: 'Rule 9(1) (Min 1.5mm for mandatory declarations)',
  },
  {
    field: 'consumer_care',
    label: 'Consumer Care Readability',
    detected_height_mm: 1.6,
    required_height_mm: 1.5,
    status: 'REVIEW',
    standard_rule: 'Rule 9(1) & Contrast Ratio Guard',
  },
];

// ── Seeded Rules (PCR-001 to PCR-010) Evaluated Results ─────────────────────
const demoResults: RuleEvaluationDetail[] = [
  {
    rule_id: 1,
    rule_code: 'PCR-001',
    rule_number: '6(1)(a)',
    title: 'Manufacturer / Packer Information',
    status: 'PASS',
    field: 'manufacturer_name',
    extracted_value: 'NutriFoods India Pvt Ltd, Industrial Area, Pune 411018',
    normalized_value: 'NutriFoods India Pvt Ltd, Industrial Area, Pune 411018',
    expected_value: 'Present & complete physical address',
    message: 'Mandatory declaration detected and address completeness verified.',
    severity: 'HIGH',
    confidence: 0.98,
    source_reference: 'Rule 6(1)(a), Legal Metrology (Packaged Commodities) Rules, 2011',
    evidence: {
      field: 'manufacturer_name',
      raw_value: 'NutriFoods India Pvt Ltd, Industrial Area, Pune 411018',
      confidence: 0.98,
      source_image: 'front_label.jpg',
      bounding_box: [12, 10, 75, 14],
    },
  },
  {
    rule_id: 2,
    rule_code: 'PCR-002',
    rule_number: '6(1)(b)',
    title: 'Generic or Common Name of Commodity',
    status: 'PASS',
    field: 'commodity_description',
    extracted_value: 'Almond Butter Cookies',
    normalized_value: 'Almond Butter Cookies',
    expected_value: 'Generic name (min 2 characters)',
    message: 'Generic commodity name declared prominently on principal display panel.',
    severity: 'HIGH',
    confidence: 0.96,
    source_reference: 'Rule 6(1)(b), Legal Metrology (Packaged Commodities) Rules, 2011',
    evidence: {
      field: 'commodity_description',
      raw_value: 'Almond Butter Cookies',
      confidence: 0.96,
      source_image: 'front_label.jpg',
      bounding_box: [30, 10, 60, 10],
    },
  },
  {
    rule_id: 3,
    rule_code: 'PCR-003',
    rule_number: '6(1)(c)',
    title: 'Net Quantity Numeric Declaration',
    status: 'PASS',
    field: 'net_quantity',
    extracted_value: '150 g',
    normalized_value: { value: 150, unit: 'g' },
    expected_value: 'Numeric value > 0',
    message: 'Net quantity is positive numeric float (150.0). Satisfies positive declaration requirement.',
    severity: 'HIGH',
    confidence: 0.95,
    source_reference: 'Rule 6(1)(c), Legal Metrology (Packaged Commodities) Rules, 2011',
    evidence: {
      field: 'net_quantity',
      raw_value: '150 g',
      confidence: 0.95,
      source_image: 'front_label.jpg',
      bounding_box: [44, 10, 35, 9],
    },
  },
  {
    rule_id: 4,
    rule_code: 'PCR-004',
    rule_number: '12 & Second Schedule',
    title: 'Standard Metric Units',
    status: 'PASS',
    field: 'net_quantity',
    extracted_value: '150 g',
    normalized_value: 'g',
    expected_value: 'Standard unit: mg, g, kg, ml, l, N, U',
    message: "Unit 'g' conforms to Schedule II standard metric symbols. Non-standard symbols (gms, gm) rejected.",
    severity: 'HIGH',
    confidence: 0.95,
    source_reference: 'Rule 12 & Second Schedule, Legal Metrology (Packaged Commodities) Rules, 2011',
    evidence: {
      field: 'net_quantity',
      raw_value: '150 g',
      confidence: 0.95,
      source_image: 'front_label.jpg',
      bounding_box: [44, 10, 35, 9],
    },
  },
  {
    rule_id: 5,
    rule_code: 'PCR-005',
    rule_number: '6(1)(d)',
    title: 'Month and Year of Manufacture / Packing',
    status: 'PASS',
    field: 'month_year',
    extracted_value: '08/2026',
    normalized_value: '08/2026',
    expected_value: 'MM/YYYY format regex',
    message: 'Date matches statutory format regex ^(0[1-9]|1[0-2])\\/?(20\\d{2}|\\d{2})$.',
    severity: 'HIGH',
    confidence: 0.92,
    source_reference: 'Rule 6(1)(d), Legal Metrology (Packaged Commodities) Rules, 2011',
    evidence: {
      field: 'month_year',
      raw_value: '08/2026',
      confidence: 0.92,
      source_image: 'front_label.jpg',
      bounding_box: [57, 10, 40, 8],
    },
  },
  {
    rule_id: 6,
    rule_code: 'PCR-006',
    rule_number: '6(1)(e)',
    title: 'Maximum Retail Price (MRP) Declaration',
    status: 'FAIL',
    field: 'mrp',
    extracted_value: undefined,
    normalized_value: undefined,
    expected_value: 'MRP Rs. XX.XX (inclusive of all taxes)',
    message: "Mandatory declaration 'mrp' was not detected on package label. Explicit statutory violation.",
    severity: 'HIGH',
    confidence: undefined,
    source_reference: 'Rule 6(1)(e), Legal Metrology (Packaged Commodities) Rules, 2011',
    evidence: undefined,
  },
  {
    rule_id: 7,
    rule_code: 'PCR-007',
    rule_number: '6(1)(da)',
    title: 'Country of Origin for Imported Commodities',
    status: 'NOT_APPLICABLE',
    field: 'country_of_origin',
    extracted_value: 'India',
    normalized_value: false,
    expected_value: 'Condition: is_imported equals True',
    message: "Rule not applicable: Condition 'is_imported equals True' was not satisfied (Commodity is Domestic).",
    severity: 'HIGH',
    confidence: 1.0,
    source_reference: 'Rule 6(1)(da), Legal Metrology (Packaged Commodities) Amendment Rules, 2017',
    evidence: undefined,
  },
  {
    rule_id: 8,
    rule_code: 'PCR-008',
    rule_number: '6(1)(a) proviso',
    title: 'Importer Name and Address',
    status: 'NOT_APPLICABLE',
    field: 'importer_name',
    extracted_value: undefined,
    normalized_value: false,
    expected_value: 'Condition: is_imported equals True',
    message: "Rule not applicable: Domestic package does not require importer identification.",
    severity: 'HIGH',
    confidence: undefined,
    source_reference: 'Rule 6(1)(a) Proviso, Legal Metrology (Packaged Commodities) Rules, 2011',
    evidence: undefined,
  },
  {
    rule_id: 9,
    rule_code: 'PCR-009',
    rule_number: '6(1)(f)',
    title: 'Consumer Care Grievance Redressal Contact',
    status: 'REVIEW',
    field: 'consumer_care',
    extracted_value: 'Tel: 1800-222-333',
    normalized_value: 'Tel: 1800-222-333',
    expected_value: 'Phone / Email / Address for grievance redressal',
    message: 'OCR confidence (0.72) is below trusted threshold (0.85). Human inspector verification is required.',
    severity: 'MEDIUM',
    confidence: 0.72,
    source_reference: 'Rule 6(1)(f), Legal Metrology (Packaged Commodities) Rules, 2011',
    evidence: {
      field: 'consumer_care',
      raw_value: 'Tel: 1800-222-333',
      confidence: 0.72,
      source_image: 'back_label.jpg',
      bounding_box: [68, 10, 80, 18],
    },
  },
  {
    rule_id: 10,
    rule_code: 'PCR-010',
    rule_number: '6(1)(d) & FSSAI',
    title: 'Food Category Expiry / Packing Declaration',
    status: 'PASS',
    field: 'date_of_manufacture',
    extracted_value: '08/2026',
    normalized_value: '08/2026',
    expected_value: 'Mandatory for category: FOOD',
    message: 'Food commodity packing/expiry declaration present and legally valid.',
    severity: 'HIGH',
    confidence: 0.92,
    source_reference: 'Rule 6(1)(d) second proviso, Legal Metrology (Packaged Commodities) Rules, 2011',
    evidence: {
      field: 'date_of_manufacture',
      raw_value: '08/2026',
      confidence: 0.92,
      source_image: 'front_label.jpg',
      bounding_box: [57, 10, 40, 8],
    },
  },
];

const demoViolations: ViolationDetail[] = [
  {
    rule_code: 'PCR-006',
    rule_number: '6(1)(e)',
    field: 'mrp',
    severity: 'HIGH',
    violation_message: "Mandatory declaration 'mrp' was not detected on package label.",
    evidence: undefined,
  },
];

export const DEMO_REPORT: ComplianceReport = {
  scan_id: 1,
  product_name: 'NutriCrunch Almond Butter Cookies',
  category: 'FOOD',
  is_imported: false,
  overall_status: 'NON_COMPLIANT',
  summary: {
    total_rules: 10,
    passed: 6,
    failed: 1,
    review: 1,
    not_applicable: 2,
    compliance_percentage: 75.0,
  },
  results: demoResults,
  violations: demoViolations,
  font_audits: DEMO_FONT_AUDITS,
};

// ── Dashboard Metrics ────────────────────────────────────────────────────────
export const DEMO_DASHBOARD = {
  totalInspections: 48,
  compliant: 32,
  violations: 12,
  reviewRequired: 4,
  recentInspections: [
    { id: 1, scan_id: 'SCN-2026-001', product: 'NutriCrunch Almond Butter Cookies', category: 'FOOD', date: '2026-09-04', status: 'NON_COMPLIANT' as const, violations: 1, inspector: 'Insp. R. Verma' },
    { id: 2, scan_id: 'SCN-2026-002', product: 'Himalayan Herbal Green Tea 100g', category: 'FOOD', date: '2026-09-03', status: 'COMPLIANT' as const, violations: 0, inspector: 'Insp. S. Patnaik' },
    { id: 3, scan_id: 'SCN-2026-003', product: 'LuxeGlow Botanical Face Cream 50g', category: 'COSMETICS', date: '2026-09-03', status: 'COMPLIANT' as const, violations: 0, inspector: 'Insp. A. Nair' },
    { id: 4, scan_id: 'SCN-2026-004', product: 'TechPro Braided USB-C Cable 1.5m', category: 'ELECTRONICS', date: '2026-09-02', status: 'NEEDS_REVIEW' as const, violations: 0, inspector: 'Insp. R. Verma' },
    { id: 5, scan_id: 'SCN-2026-005', product: 'Royal Heritage Basmati Rice 5kg', category: 'FOOD', date: '2026-09-01', status: 'NON_COMPLIANT' as const, violations: 2, inspector: 'Insp. K. Rao' },
  ],
  topViolations: [
    { rule_code: 'PCR-006', title: 'MRP Declaration Missing / Format Violation', count: 9 },
    { rule_code: 'PCR-001', title: 'Incomplete Manufacturer / Packer Address', count: 5 },
    { rule_code: 'PCR-005', title: 'Non-standard Mfg / Packing Date Format', count: 4 },
    { rule_code: 'PCR-009', title: 'Unreachable / Incomplete Consumer Care Details', count: 3 },
    { rule_code: 'PCR-004', title: 'Non-metric Measurement Unit (e.g. gms, kgs)', count: 2 },
  ],
};
